infracost test7

diff --git a/.github/workflows/infracost.yml b/.github/workflows/infracost.yml
--- a/.github/workflows/infracost.yml
+++ b/.github/workflows/infracost.yml
@@ -2,48 +2,30 @@ name: Infracost Workflow
 
 on:
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, synchronize, closed]
   push:
     branches:
       - main
 
 jobs:
-  infracost:
+  infracost-default-branch-update:
+
+    name: Infracost Default Branch Update
+    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master')
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: write  # PR에 주석을 추가하기 위해 필요함.
-      
     steps:
-      # Infracost CLI 설치
       - name: Setup Infracost
         uses: infracost/actions/setup@v3
         with:
           api-key: ${{ secrets.INFRACOST_API_KEY }}
-      
-      # 코드 체크아웃
-      - name: Checkout Code
+
+      - name: Checkout main/master branch
         uses: actions/checkout@v4
 
-      # 비용 분석 수행
-      - name: Run Infracost
+      - name: Run Infracost on default branch and update Infracost Cloud
         run: |
           infracost breakdown --path=. \
-                              --format=json \
-                              --out-file=infracost-report.json
+                    --format=json \
+                    --out-file=infracost.json
 
-      # PR에 비용 분석 결과 주석 추가
-      - name: Post Infracost Comment
-        if: github.event_name == 'pull_request'
-        run: |
-          infracost comment github --path=infracost-report.json \
-                                   --repo=$GITHUB_REPOSITORY \
-                                   --github-token=${{ github.token }} \
-                                   --pull-request=${{ github.event.pull_request.number }} \
-                                   --behavior=update
-
-      # main 브랜치에 푸시된 결과를 Infracost Cloud에 업로드
-      - name: Upload Infracost Report to Cloud
-        if: github.event_name == 'push'
-        run: |
-          infracost upload --path=infracost-report.json || echo "Upload to Infracost Cloud failed, continuing workflow"
+          infracost upload --path=infracost.json || echo "Always pass main branch runs even if there are policy failures"
